// Generate p04 Maestro flow from RISK_COMMENT_FIELDS_AUTOMATED (single source of truth, shared
// with setup-data's expected.riskAssessment so the flow and the verify can never drift).
// Run: node scripts/parity/gen-p04.mjs  -> writes mobile-flows-parity/p04_mobile2web_risk_assessment.yaml
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { RISK_COMMENT_FIELDS_AUTOMATED } from "./setup-data.mjs";

const VALUE = "PARITY-${RUN_ID} rc"; // must equal buildExpected().riskAssessment[*]

function fieldSteps(label) {
  // scroll the RA form to the label, tap the input below it, type, defocus (tap label) so onBlur
  // commits. NOTE: no centerElement here — on the CI emulator centering the label made "below"
  // miss the input (value not persisted). This simple form is the proven-stable baseline and
  // works because the automated field sits right under the Risk Assessment header (on-screen).
  return [
    `- scrollUntilVisible:`,
    `    element: { text: ${JSON.stringify(label)} }`,
    `    direction: DOWN`,
    `    timeout: 15000`,
    `- tapOn:`,
    `    below: { text: ${JSON.stringify(label)} }`,
    `- inputText: ${JSON.stringify(VALUE)}`,
    `- hideKeyboard`,
    `- tapOn: ${JSON.stringify(label)}`,
  ];
}

export function buildP04() {
  const head = [
    `appId: com.hydrocert.app`,
    `name: "PARITY p04 - mobile-to-web risk assessment comment field(s)"`,
    `tags: [parity, mobile2web]`,
    `---`,
    `# GENERATED by scripts/parity/gen-p04.mjs from RISK_COMMENT_FIELDS_AUTOMATED — do not edit by hand.`,
    `- runFlow: _shared/open_inspection.yaml`,
    `- scrollUntilVisible:`,
    `    element: { text: "Risk Assessment" }`,
    `    direction: DOWN`,
    `    timeout: 20000`,
    `- tapOn: "Risk Assessment"`,
  ];
  const body = RISK_COMMENT_FIELDS_AUTOMATED.flatMap(fieldSteps);
  const tail = [
    `# Risk Assessment is the last card -> after the final field, Save sits just below. Scroll`,
    `# DOWN to it directly (collapsing by scrolling UP to the header is unreliable from the`,
    `# bottom of this very long card). Save is the last meaningful step; the API readback in`,
    `# verify-data.mjs is the source of truth, so no trailing scroll-back is needed.`,
    `- scrollUntilVisible:`,
    `    element: { text: "^Save$" }`,
    `    direction: DOWN`,
    `    timeout: 30000`,
    `    speed: 40`,
    `- tapOn: "^Save$"`,
    `- waitForAnimationToEnd:`,
    `    timeout: 5000`,
  ];
  return [...head, ...body, ...tail].join("\n") + "\n";
}

if (import.meta.url === `file://${process.argv[1]}` || import.meta.url.endsWith(process.argv[1]?.replace(/\\/g, "/"))) {
  const out = fileURLToPath(new URL("../../mobile-flows-parity/p04_mobile2web_risk_assessment.yaml", import.meta.url));
  writeFileSync(out, buildP04());
  console.log(`p04 generated: ${RISK_COMMENT_FIELDS_AUTOMATED.length} field(s) -> ${out}`);
}
