// Render report.html from summary.json (qa-parity report style).
import { writeFileSync, readFileSync } from "node:fs";

export function renderReport(s) {
  // Verdict follows the gate (hard failures only). Fall back to failed>0 for legacy summaries.
  const gateFail = s.gateFailed ?? (s.failed > 0);
  const overall = gateFail ? "ATTENTION" : "PASS";
  const badge = (v) => `<span class="b ${v.toLowerCase().includes("pass") ? "pass" : "fail"}">${v}</span>`;
  const rows = s.checks.map((c) => {
    // 2c is an API-only backend create->read check (mobile doesn't render inspection actions, F-01).
    // Flag it so it doesn't read as cross-platform parity (L5).
    const note = String(c.id).startsWith("2c") ? ' <em style="color:#9ca3af">(API-only · known mobile-render gap F-01)</em>' : "";
    return `<tr><td><code>${c.id}</code>${note}</td><td>${c.direction}</td><td>${badge(c.status)}</td><td>${(c.details || "").replace(/</g, "&lt;")}</td></tr>`;
  }).join("");
  // Parity-only score excludes the 2c tautology so it can't inflate the headline coverage (L5).
  const parity = s.checks.filter((c) => !String(c.id).startsWith("2c"));
  const parityPass = parity.filter((c) => c.status === "PASS").length;
  return `<!doctype html><meta charset="utf-8"><title>Parity ${s.runId}</title>
<style>body{font:14px system-ui,Segoe UI,Arial;margin:24px;color:#111}
.banner{padding:16px 20px;border-radius:8px;font-size:20px;font-weight:600;color:#fff;background:${gateFail ? "#dc2626" : "#16a34a"}}
table{border-collapse:collapse;margin-top:16px;width:100%}td,th{border:1px solid #e5e7eb;padding:8px 10px;text-align:left;font-size:13px}
th{background:#f9fafb}.b{padding:2px 8px;border-radius:4px;color:#fff;font-size:12px;font-weight:600}
.b.pass{background:#16a34a}.b.fail{background:#dc2626}code{background:#f3f4f6;padding:1px 5px;border-radius:3px}
.grid{display:flex;gap:28px;margin-top:12px;color:#374151;flex-wrap:wrap}</style>
<div class="banner">${s.passed}/${s.total} PASS — ${overall}</div>
<div class="grid"><div>Run: <code>${s.runId}</code></div><div>Visit: <code>${s.visitRef}</code></div>
<div>Parity (excl. 2c known-gap): ${parityPass}/${parity.length}</div>
<div>Gate: <strong>${gateFail ? "FAIL" : "PASS"}</strong></div>
<div>Passed: ${s.passed}</div><div>Failed: ${s.failed}</div></div>
<table><tr><th>Check</th><th>Direction</th><th>Result</th><th>Details</th></tr>${rows}</table>
<footer style="margin-top:24px;color:#9ca3af">Generated by Hydro-QA bidirectional-parity — run ${s.runId}</footer>`;
}

if (import.meta.url === `file://${process.argv[1]}` || import.meta.url.endsWith(process.argv[1]?.replace(/\\/g, "/"))) {
  const s = JSON.parse(readFileSync("summary.json"));
  writeFileSync("report.html", renderReport(s));
  console.log("report.html written");
}
