// Generate p04 Maestro flow from RISK_COMMENT_FIELDS (single source of truth).
// Run: node scripts/parity/gen-p04.mjs  -> writes mobile-flows-parity/p04_mobile2web_risk_assessment.yaml
// Keeps the 18-field Maestro flow in sync with setup-data's expected.riskAssessment.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { RISK_COMMENT_FIELDS } from "./setup-data.mjs";

const VALUE = "PARITY-${RUN_ID} rc"; // must equal buildExpected().riskAssessment[*]

function fieldSteps(label) {
  // scroll the long RA form to each label, type, defocus (tap label) so onBlur commits.
  // centerElement keeps the label mid-screen so its input field (rendered just below it) is
  // on-screen for the "below" tap — without it, scrollUntilVisible can land the label at the
  // bottom edge with the input off-screen (fails on the smaller/slower CI emulator viewport).
  return [
    `- scrollUntilVisible:`,
    `    element: { text: ${JSON.stringify(label)} }`,
    `    direction: DOWN`,
    `    timeout: 20000`,
    `    centerElement: true`,
    `- tapOn:`,
    `    below: { text: ${JSON.stringify(label)} }`,
    `- inputText: ${JSON.stringify(VALUE)}`,
    `- hideKeyboard`,
    `- tapOn: ${JSON.stringify(label)}`,
  ];
}

export function buildP04() {
  const head = [
    `appId: com.hydrocert.app`,
    `name: "PARITY p04 - mobile-to-web risk assessment (18 comment fields)"`,
    `tags: [parity, mobile2web]`,
    `---`,
    `# GENERATED by scripts/parity/gen-p04.mjs from RISK_COMMENT_FIELDS — do not edit by hand.`,
    `- runFlow: _shared/open_inspection.yaml`,
    `- scrollUntilVisible:`,
    `    element: { text: "Risk Assessment" }`,
    `    direction: DOWN`,
    `    timeout: 20000`,
    `- tapOn: "Risk Assessment"`,
  ];
  const body = RISK_COMMENT_FIELDS.flatMap(fieldSteps);
  const tail = [
    `# Risk Assessment is the last card -> after the final field, Save sits just below. Scroll`,
    `# DOWN to it directly (collapsing by scrolling UP to the header is unreliable from the`,
    `# bottom of this very long card). Save is the last meaningful step; the API readback in`,
    `# verify-data.mjs is the source of truth, so no trailing scroll-back is needed.`,
    `- scrollUntilVisible:`,
    `    element: { text: "^Save$" }`,
    `    direction: DOWN`,
    `    timeout: 30000`,
    `    speed: 40`,
    `- tapOn: "^Save$"`,
    `- waitForAnimationToEnd:`,
    `    timeout: 5000`,
  ];
  return [...head, ...body, ...tail].join("\n") + "\n";
}

if (import.meta.url === `file://${process.argv[1]}` || import.meta.url.endsWith(process.argv[1]?.replace(/\\/g, "/"))) {
  const out = fileURLToPath(new URL("../../mobile-flows-parity/p04_mobile2web_risk_assessment.yaml", import.meta.url));
  writeFileSync(out, buildP04());
  console.log(`p04 generated: ${RISK_COMMENT_FIELDS.length} fields -> ${out}`);
}
